### ISSUE TITLE
High CPU Utilization Kafka Connect Bigquery

### ISSUE THREAD

**Issue by skumarlabs** [confluentinc/kafka-connect-bigquery#79] opened 2021-02-01 07:59 UTC
My Kafka cluster Streaming CDC data into Bigquery has suddenly started giving below errors and the CPU utilization has increased to >80% than normally 20-30%. I am not able to figure out anything from stack trace logs. Any suggestions? thanks in advance!

`
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,050] ERROR WorkerSinkTask{id=cdc-bq-sink-all-1} Commit of offsets threw an unexpected exception for sequence number 99: null (org.apache.kafka.connect.runtime.WorkerSinkTask:264)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: Some write threads encountered unrecoverable errors: com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException; See logs for more detail
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor.awaitCurrentTasks(KCBQThreadPoolExecutor.java:97)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:127)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:389)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:213)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.lang.Thread.run(Thread.java:748)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,219] INFO Putting 0 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,221] INFO Putting 2 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,225] INFO Putting 1 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,239] INFO Putting 194 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,493] INFO Putting 500 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)

Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,770] INFO Putting 500 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask:187)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: [2021-02-01 07:36:29,801] ERROR Task failed with com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException error: table insertion failed for the following rows:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 0]: stopped:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 1]: stopped:
...
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 14]: stopped:
**Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 15]: invalid: Missing required field: Msg_0_CLOUD_QUERY_TABLE.qr_filename.**
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 16]: stopped:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 17]: stopped:
...
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 41]: stopped:  (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor:68)
**Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]: Exception in thread "pool-10-thread-101" com.wepay.kafka.connect.bigquery.exception.BigQueryConnectException: table insertion failed for the following rows:**
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 0]: stopped:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 1]: stopped:
...
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 14]: stopped:
**Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 15]: invalid: Missing required field: Msg_0_CLOUD_QUERY_TABLE.qr_filename.**
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 16]: stopped:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 17]: stopped:
...
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         [row index 41]: stopped:
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:131)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:80)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Feb 01 07:36:29 kafka-cluster-2 connect-distributed[17558]:         at java.lang.Thread.run(Thread.java:748)
`

**Comment by C0urante** [comment] 2021-02-02 22:36
@skumarlabs what version of the connector are you running?

**Comment by skumarlabs** [comment] 2021-02-03 05:09
@C0urante I am using version 1.6.1. and it was working fine till now.

**Comment by C0urante** [comment] 2021-02-16 15:40
@skumarlabs sorry for the delay in response. It looks like this is caused by some kind of schema misalignment between what's in Kafka and the table in BigQuery. The connector should fail in this situation instead of hogging CPU; this should should be fixed by the changes from https://github.com/confluentinc/kafka-connect-bigquery/pull/14, which are present in the 1.6.6 release of the connector.

**Closed by C0urante** 2021-02-16 15:40 UTC
Labels: question
