### ISSUE TITLE
Support for BQ Storage Streaming Write API

### ISSUE THREAD

**Issue by nmatare** [confluentinc/kafka-connect-bigquery#169] opened 2021-12-08 19:55 UTC
Google is deprecating the legacy InsertAll method in favor of the newer BigQuery Storage Streaming Write API (v1 or v2)

It would be wonderful if Confluent would support this newer upload method...

ref:  https://cloud.google.com/bigquery/docs/write-api

**Comment by C0urante** [comment] 2021-12-08 19:59
Duplicate of https://github.com/confluentinc/kafka-connect-bigquery/issues/100.

But noted :)

**Closed by C0urante** 2021-12-08 19:59 UTC
